version: "3.8"

services:

  backend:
    build: .
    container_name: backend
    tty: true
    stdin_open: true
    restart: always
    env_file: .env
    depends_on:
      - memcached
      - rabbitmq
    ports:
      - "8000:8000"
    volumes:
      - ./:/srv/project

  memcached:
    image: memcached:1.6.8
    container_name: memcached
    tty: true
    stdin_open: true
    restart: always

  rabbitmq:
    image: rabbitmq:3.8-rc-management
    container_name: rabbitmq
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "15672:15672"
    env_file: .env
