# Generated by Django 2.2.16 on 2020-12-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_urltracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urltracker',
            name='path',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
