# Generated by Django 2.2.16 on 2020-11-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_auto_20201018_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Dollar'), (2, 'Euro')], db_index=True),
        ),
        migrations.AlterIndexTogether(
            name='rate',
            index_together={('currency', 'source')},
        ),
    ]
