# Generated by Django 2.2.16 on 2020-12-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0004_auto_20201129_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'permissions': [('full_edit', 'This permission allows user to update all available fields in Rate model')]},
        ),
    ]
